# Generated by Django 2.2.7 on 2020-05-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200330_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
