# Generated by Django 2.2.7 on 2020-02-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0003_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='type',
            field=models.CharField(default='upvote', max_length=10),
            preserve_default=False,
        ),
    ]
