# Generated by Django 2.2.7 on 2020-03-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0012_auto_20200312_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
