# Generated by Django 2.2.7 on 2020-03-13 21:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('socialcoder', '0014_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
