# Generated by Django 2.2.7 on 2020-03-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('socialcoder', '0015_examplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialcoder.ExampleModel'),
        ),
    ]
