# Generated by Django 2.2.7 on 2020-03-13 21:33

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('socialcoder', '0016_post_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleModel',
            new_name='CodeSnippet',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='test',
            new_name='code',
        ),
    ]
