# Generated by Django 2.2.7 on 2020-03-13 22:54

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0017_auto_20200313_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
