# Generated by Django 2.2.7 on 2020-03-13 22:55

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0018_auto_20200313_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='codesnippet',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='no code'),
            preserve_default=False,
        ),
    ]
