# Generated by Django 2.2.7 on 2020-03-14 15:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0019_auto_20200313_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='codesnippet',
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
