# Generated by Django 2.2.7 on 2020-03-14 15:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0020_auto_20200314_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
