# Generated by Django 2.2.7 on 2020-03-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0023_post_code_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='code_snippet',
        ),
    ]
