# Generated by Django 2.2.7 on 2020-03-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0024_remove_post_code_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
