# Generated by Django 2.2.7 on 2020-03-15 17:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0025_remove_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
        migrations.AddField(
            model_name='response',
            name='code',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
