# Generated by Django 2.2.7 on 2020-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0026_auto_20200315_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='category_pics'),
        ),
    ]
