# Generated by Django 2.2.7 on 2020-04-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0029_auto_20200402_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ranking',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
