# Generated by Django 2.2.7 on 2020-04-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0030_post_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
