# Generated by Django 2.2.7 on 2020-04-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialcoder', '0033_auto_20200414_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='score',
            new_name='ranking',
        ),
    ]
